#!/usr/bin/env python

from sys import argv
from configobj import ConfigObj

# add always some kind of documentation and check on the input

# git config --remove-section submodule.$SUBMOD
# git rm --cached $SUBMOD
# echo "now remove the file from .gitmodules"

# Local Variables:
# mode: python
# End:
